namespace HelloWorlds.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RemoveInsertedUpdatedBy : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Cities", "InsertedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.CityTypes", "InsertedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.CityTypes", "UpdatedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.Cities", "UpdatedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.Countries", "InsertedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.States", "InsertedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.StateTypes", "InsertedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.StateTypes", "UpdatedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.States", "UpdatedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.CountryTypes", "InsertedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.CountryTypes", "UpdatedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.Countries", "UpdatedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.FutureVisits", "InsertedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.FutureVisits", "UpdatedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.PastVisits", "InsertedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.PastVisits", "UpdatedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.Worlds", "InsertedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.WorldTypes", "InsertedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.WorldTypes", "UpdatedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.Worlds", "UpdatedBy_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.FutureVisits", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.PastVisits", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.States", "Country_Id", "dbo.Countries");
            DropForeignKey("dbo.Cities", "State_Id", "dbo.States");
            DropForeignKey("dbo.Countries", "World_Id", "dbo.Worlds");
            DropIndex("dbo.Cities", new[] { "InsertedBy_Id" });
            DropIndex("dbo.Cities", new[] { "UpdatedBy_Id" });
            DropIndex("dbo.CityTypes", new[] { "InsertedBy_Id" });
            DropIndex("dbo.CityTypes", new[] { "UpdatedBy_Id" });
            DropIndex("dbo.Countries", new[] { "InsertedBy_Id" });
            DropIndex("dbo.Countries", new[] { "UpdatedBy_Id" });
            DropIndex("dbo.States", new[] { "InsertedBy_Id" });
            DropIndex("dbo.States", new[] { "UpdatedBy_Id" });
            DropIndex("dbo.StateTypes", new[] { "InsertedBy_Id" });
            DropIndex("dbo.StateTypes", new[] { "UpdatedBy_Id" });
            DropIndex("dbo.CountryTypes", new[] { "InsertedBy_Id" });
            DropIndex("dbo.CountryTypes", new[] { "UpdatedBy_Id" });
            DropIndex("dbo.FutureVisits", new[] { "InsertedBy_Id" });
            DropIndex("dbo.FutureVisits", new[] { "UpdatedBy_Id" });
            DropIndex("dbo.PastVisits", new[] { "InsertedBy_Id" });
            DropIndex("dbo.PastVisits", new[] { "UpdatedBy_Id" });
            DropIndex("dbo.Worlds", new[] { "InsertedBy_Id" });
            DropIndex("dbo.Worlds", new[] { "UpdatedBy_Id" });
            DropIndex("dbo.WorldTypes", new[] { "InsertedBy_Id" });
            DropIndex("dbo.WorldTypes", new[] { "UpdatedBy_Id" });
            DropPrimaryKey("dbo.Cities");
            DropPrimaryKey("dbo.Countries");
            DropPrimaryKey("dbo.States");
            DropPrimaryKey("dbo.FutureVisits");
            DropPrimaryKey("dbo.PastVisits");
            DropPrimaryKey("dbo.Worlds");
            AlterColumn("dbo.Cities", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Countries", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.States", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.FutureVisits", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.PastVisits", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Worlds", "Id", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.Cities", "Id");
            AddPrimaryKey("dbo.Countries", "Id");
            AddPrimaryKey("dbo.States", "Id");
            AddPrimaryKey("dbo.FutureVisits", "Id");
            AddPrimaryKey("dbo.PastVisits", "Id");
            AddPrimaryKey("dbo.Worlds", "Id");
            AddForeignKey("dbo.FutureVisits", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.PastVisits", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.States", "Country_Id", "dbo.Countries", "Id");
            AddForeignKey("dbo.Cities", "State_Id", "dbo.States", "Id");
            AddForeignKey("dbo.Countries", "World_Id", "dbo.Worlds", "Id");
            DropColumn("dbo.Cities", "InsertedBy_Id");
            DropColumn("dbo.Cities", "UpdatedBy_Id");
            DropColumn("dbo.CityTypes", "InsertedBy_Id");
            DropColumn("dbo.CityTypes", "UpdatedBy_Id");
            DropColumn("dbo.Countries", "InsertedBy_Id");
            DropColumn("dbo.Countries", "UpdatedBy_Id");
            DropColumn("dbo.States", "InsertedBy_Id");
            DropColumn("dbo.States", "UpdatedBy_Id");
            DropColumn("dbo.StateTypes", "InsertedBy_Id");
            DropColumn("dbo.StateTypes", "UpdatedBy_Id");
            DropColumn("dbo.CountryTypes", "InsertedBy_Id");
            DropColumn("dbo.CountryTypes", "UpdatedBy_Id");
            DropColumn("dbo.FutureVisits", "InsertedBy_Id");
            DropColumn("dbo.FutureVisits", "UpdatedBy_Id");
            DropColumn("dbo.PastVisits", "InsertedBy_Id");
            DropColumn("dbo.PastVisits", "UpdatedBy_Id");
            DropColumn("dbo.Worlds", "InsertedBy_Id");
            DropColumn("dbo.Worlds", "UpdatedBy_Id");
            DropColumn("dbo.WorldTypes", "InsertedBy_Id");
            DropColumn("dbo.WorldTypes", "UpdatedBy_Id");
        }
        
        public override void Down()
        {
            AddColumn("dbo.WorldTypes", "UpdatedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.WorldTypes", "InsertedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Worlds", "UpdatedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Worlds", "InsertedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PastVisits", "UpdatedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PastVisits", "InsertedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.FutureVisits", "UpdatedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.FutureVisits", "InsertedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CountryTypes", "UpdatedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CountryTypes", "InsertedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StateTypes", "UpdatedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StateTypes", "InsertedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.States", "UpdatedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.States", "InsertedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Countries", "UpdatedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Countries", "InsertedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CityTypes", "UpdatedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CityTypes", "InsertedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Cities", "UpdatedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Cities", "InsertedBy_Id", c => c.String(maxLength: 128));
            DropForeignKey("dbo.Countries", "World_Id", "dbo.Worlds");
            DropForeignKey("dbo.Cities", "State_Id", "dbo.States");
            DropForeignKey("dbo.States", "Country_Id", "dbo.Countries");
            DropForeignKey("dbo.PastVisits", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.FutureVisits", "City_Id", "dbo.Cities");
            DropPrimaryKey("dbo.Worlds");
            DropPrimaryKey("dbo.PastVisits");
            DropPrimaryKey("dbo.FutureVisits");
            DropPrimaryKey("dbo.States");
            DropPrimaryKey("dbo.Countries");
            DropPrimaryKey("dbo.Cities");
            AlterColumn("dbo.Worlds", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.PastVisits", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.FutureVisits", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.States", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Countries", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Cities", "Id", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.Worlds", "Id");
            AddPrimaryKey("dbo.PastVisits", "Id");
            AddPrimaryKey("dbo.FutureVisits", "Id");
            AddPrimaryKey("dbo.States", "Id");
            AddPrimaryKey("dbo.Countries", "Id");
            AddPrimaryKey("dbo.Cities", "Id");
            CreateIndex("dbo.WorldTypes", "UpdatedBy_Id");
            CreateIndex("dbo.WorldTypes", "InsertedBy_Id");
            CreateIndex("dbo.Worlds", "UpdatedBy_Id");
            CreateIndex("dbo.Worlds", "InsertedBy_Id");
            CreateIndex("dbo.PastVisits", "UpdatedBy_Id");
            CreateIndex("dbo.PastVisits", "InsertedBy_Id");
            CreateIndex("dbo.FutureVisits", "UpdatedBy_Id");
            CreateIndex("dbo.FutureVisits", "InsertedBy_Id");
            CreateIndex("dbo.CountryTypes", "UpdatedBy_Id");
            CreateIndex("dbo.CountryTypes", "InsertedBy_Id");
            CreateIndex("dbo.StateTypes", "UpdatedBy_Id");
            CreateIndex("dbo.StateTypes", "InsertedBy_Id");
            CreateIndex("dbo.States", "UpdatedBy_Id");
            CreateIndex("dbo.States", "InsertedBy_Id");
            CreateIndex("dbo.Countries", "UpdatedBy_Id");
            CreateIndex("dbo.Countries", "InsertedBy_Id");
            CreateIndex("dbo.CityTypes", "UpdatedBy_Id");
            CreateIndex("dbo.CityTypes", "InsertedBy_Id");
            CreateIndex("dbo.Cities", "UpdatedBy_Id");
            CreateIndex("dbo.Cities", "InsertedBy_Id");
            AddForeignKey("dbo.Countries", "World_Id", "dbo.Worlds", "Id");
            AddForeignKey("dbo.Cities", "State_Id", "dbo.States", "Id");
            AddForeignKey("dbo.States", "Country_Id", "dbo.Countries", "Id");
            AddForeignKey("dbo.PastVisits", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.FutureVisits", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.Worlds", "UpdatedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.WorldTypes", "UpdatedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.WorldTypes", "InsertedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Worlds", "InsertedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.PastVisits", "UpdatedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.PastVisits", "InsertedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.FutureVisits", "UpdatedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.FutureVisits", "InsertedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Countries", "UpdatedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.CountryTypes", "UpdatedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.CountryTypes", "InsertedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.States", "UpdatedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.StateTypes", "UpdatedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.StateTypes", "InsertedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.States", "InsertedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Countries", "InsertedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Cities", "UpdatedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.CityTypes", "UpdatedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.CityTypes", "InsertedBy_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Cities", "InsertedBy_Id", "dbo.AspNetUsers", "Id");
        }
    }
}
